server.port: 8081

spring:
  application.name: my_task_tracker
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:testdb #jdbc:h2:file:/testdb
    username: sa
    platform: h2